version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: buy-recipe-mysql
    environment:
      MYSQL_DATABASE: buyrecipe
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_USER: buyrecipe
      MYSQL_PASSWORD: buyrecipe123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - buyrecipe-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: buy-recipe-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/buyrecipe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: buyrecipe
      SPRING_DATASOURCE_PASSWORD: buyrecipe123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
    ports:
      - "8080:8080"
    networks:
      - buyrecipe-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  buyrecipe-network:
    driver: bridge